import { StyleSheet, Platform } from 'react-native';

export const createGlobalStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    glassCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      marginVertical: 8,
      marginHorizontal: 16,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.border + '33',
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      marginVertical: 6,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: colors.textPrimary,
      textAlign: 'right',
    },
    subtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: 'right',
      marginTop: 4,
    },
    input: {
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: Platform.OS === 'ios' ? 14 : 10,
      fontSize: 15,
      color: colors.textPrimary,
      borderWidth: 1.5,
      borderColor: colors.border,
      textAlign: 'right',
    },
    buttonPrimary: {
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    buttonText: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.primaryDark,
    },
    chip: {
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 20,
      backgroundColor: colors.chipBackground,
      marginRight: 8,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border + '55',
    },
    chipText: {
      fontSize: 13,
      color: colors.chipText,
      fontWeight: '600',
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textPrimary,
      textAlign: 'right',
      marginBottom: 12,
    },
  });
